version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: job_market-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: job_board
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build:
      context: ./fastapi
    container_name: job_market-api
    environment:
      DATABASE_URL: "mysql+aiomysql://user:password@db:3306/job_board"
    ports:
      - "8000:8000"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '512M' 
