version: '3.8'

services:
  db:
    build: ./mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: job_board
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  api:
    build: ./fastapi
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "mysql+aiomysql://user:password@db/job_board"
    depends_on:
      - db
