# Fichier YAML pour le déploiement Kubernetes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-board
spec:
  replicas: 3
  selector:
    matchLabels:
      app: job-board
  template:
    metadata:
      labels:
        app: job-board
    spec:
      containers:
        - name: job-board
          image: job-board-app:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "mysql+aiomysql://user:password@mysql-service/job_board"
---
apiVersion: v1
kind: Service
metadata:
  name: job-board-service
spec:
  selector:
    app: job-board
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
