apiVersion: v1
kind: Service
metadata:
  name: job-board-service
  namespace: job-board
spec:
  selector:
    app: job-board
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer
